import { NewRowData, RowData } from './types';
import { dataToTree } from './utils';

export const data: RowData[] = [
  {
    id: 1,
    title: 'title0',
    unit: 'kg',
    quantity: 0,
    unitPrice: 0,
    price: 1209122.5,
    parent: null,
    type: 'level',
  },
  {
    id: 2,
    title: 'title1',
    unit: 'cm',
    quantity: 0,
    unitPrice: 0,
    price: 1209122.5,
    parent: 1,
    type: 'level',
  },
  {
    id: 3,
    title: 'title2',
    unit: 'bar',
    quantity: 1750,
    unitPrice: 108.07,
    price: 189122.5,
    parent: 2,
    type: 'row',
  },
  {
    id: 4,
    title: 'title3',
    unit: 'm',
    quantity: 1200,
    unitPrice: 850,
    price: 1020000,
    parent: 2,
    type: 'row',
  },
  {
    id: 5,
    title: 'title4',
    unit: '',
    quantity: 0,
    unitPrice: 0,
    price: 0,
    parent: 1,
    type: 'level',
  },
  {
    id: 6,
    title: 'title5',
    unit: '',
    quantity: 0,
    unitPrice: 0,
    price: 0,
    parent: 2,
    type: 'level',
  },
  {
    id: 7,
    title: 'title6',
    unit: '',
    quantity: 0,
    unitPrice: 0,
    price: 0,
    parent: 5,
    type: 'level',
  },
  {
    id: 8,
    title: 'title7',
    unit: '',
    quantity: 0,
    unitPrice: 0,
    price: 0,
    parent: 1,
    type: 'level',
  },
  {
    id: 9,
    title: 'title8',
    unit: 'bar',
    quantity: 1750,
    unitPrice: 108.07,
    price: 189122.5,
    parent: 3,
    type: 'row',
  },
];

export const { treeData, maxLevel } = dataToTree(data);

export const initialData: RowData[] = [
  {
    id: 1,
    title: '',
    unit: '',
    quantity: 0,
    unitPrice: 0,
    price: 0,
    parent: null,
    type: 'level',
  },
];

export const newInitialData: NewRowData = {
  title: '',
  unit: '',
  quantity: 0,
  unitPrice: 0,
  price: 0,
  parent: null,
  type: 'level',
};
