import { RowData } from './types';

export const data: RowData[] = [
  {
    id: 0,
    title: 'title1',
    unit: 'kg',
    quantity: 0,
    unitPrice: 0,
    price: 1209122.5,
    parent: null,
    type: 'level',
  },
  {
    id: 1,
    title: 'title2',
    unit: 'cm',
    quantity: 0,
    unitPrice: 0,
    price: 1209122.5,
    parent: 1,
    type: 'level',
  },
  {
    id: 2,
    title: 'title3',
    unit: 'bar',
    quantity: 1750,
    unitPrice: 108.07,
    price: 189122.5,
    parent: 2,
    type: 'row',
  },
  {
    id: 3,
    title: 'title4',
    unit: 'm',
    quantity: 1200,
    unitPrice: 850,
    price: 1020000,
    parent: 2,
    type: 'row',
  },
//   {
//     id: 4,
//     title: 'title5',
//     unit: '',
//     quantity: 0,
//     unitPrice: 0,
//     price: 0,
//     parent: null,
//     type: 'level',
//   },
];
